name: .NET Core CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  AZURE_WEBAPP_NAME: valyriadiscordapi
  AZURE_WEBAPP_PACKAGE_PATH: 'build'
  DOTNET_VERSION: '6.0.201'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build src/Api/Api.csproj --configuration Release
          dotnet publish src/Api/Api.csproj -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/head/master'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'